### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by kyusu** [vsaravind007/nodeScratchpad#7]
Hi,

nodeScratchpad looks really interesting and neat! But unfortunately I can not find a license anywhere.
Could you please specify under which license you're releasing it? 

Thanks!

**Comment by vsaravind007** [comment]
Hey @kyusu, thank you. Have added the license info, please check.

**Comment by kyusu** [comment]
Hi @vsaravind007, 
thanks! That was quick!
