### ISSUE TITLE
Run keyboard shortcut

### ISSUE THREAD

**Issue by webdevian** [vsaravind007/nodeScratchpad#8]
A keyboard shortcut for run would be useful, something like (cmd + enter)

**Comment by vsaravind007** [comment]
This is on top of the priority list! Thanks 👍

**Comment by vsaravind007** [comment]
Added keyboard shortcut ⌘+R to run code. Available in [version 1.1](https://github.com/vsaravind007/nodeScratchpad/releases/tag/rel-1.1) Thanks @webdevian
